# Generated by Django 5.2.1 on 2025-05-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertidaoNascimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('data_nascimento', models.DateField()),
                ('hora_nascimento', models.TimeField()),
                ('local_nascimento', models.CharField(max_length=255)),
                ('dnv', models.CharField(max_length=50, unique=True, verbose_name='Declaração de Nascido Vivo')),
                ('nome_mae', models.CharField(max_length=255)),
                ('nacionalidade_mae', models.CharField(max_length=100)),
                ('naturalidade_mae', models.CharField(max_length=100)),
                ('idade_mae', models.PositiveIntegerField()),
                ('profissao_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_mae', models.TextField()),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('nacionalidade_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('naturalidade_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('idade_pai', models.PositiveIntegerField(blank=True, null=True)),
                ('profissao_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_pai', models.TextField(blank=True, null=True)),
                ('nome_avo_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_avo_materna', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_avo_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_avo_paterna', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil_pais', models.CharField(blank=True, choices=[('Casados', 'Casados'), ('União Estável', 'União Estável'), ('Solteiros', 'Solteiros'), ('Separados', 'Separados'), ('Divorciados', 'Divorciados'), ('Outros', 'Outros')], max_length=50, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('livro', models.CharField(max_length=20)),
                ('folha', models.CharField(max_length=20)),
                ('termo', models.CharField(max_length=20)),
                ('nome_oficial_cartorio', models.CharField(max_length=255)),
                ('nome_declarante', models.CharField(max_length=255)),
            ],
        ),
    ]
